name: templeteproject
description: A new Flutter application.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.0
  mobx: ^1.2.1
  flutter_mobx: ^1.1.0
  mobx_codegen: ^1.1.0
  build_runner: ^1.10.0
  easy_localization: ^2.3.3
  provider: ^4.3.2+3
  shared_preferences: ^0.5.12+4
  dio: 3.0.10 #latest version
  json_annotation: ^3.1.1




dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/lang/


